version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
        fingerprints:
          - "42:11:ea:35:ed:54:6a:01:10:a6:b0:92:78:3f:13:0a"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build 